"""Default risk/config — all thresholds in DB, versioned via ConfigManager."""

DEFAULT_CONFIG = {
    "config_version": 2,
    "max_risk_per_trade": 0.005,
    "max_position_size_pct": 0.25,
    "max_open_positions": 2,
    "daily_loss_limit_pct": 0.02,
    "weekly_loss_limit_pct": 0.05,
    "max_drawdown_limit_pct": 0.15,
    "max_spread_pct": 0.005,
    "min_liquidity_score": 40,
    "max_loss_streak": 5,
    "confidence_threshold": 0.6,
    "stop_loss_required": True,
    "take_profit_required": False,
    "kill_switch_active": False,
    "paper_trading_only": True,
    "live_trading_enabled": False,
    "min_order_notional_usd": 1.0,
    "opening_range_minutes": 30,
    "pairs_z_entry": 2.0,
    "pairs_z_exit": 0.5,
    "slippage_assumption_pct": 0.001,
    "spread_assumption_pct": 0.0005,
    "fee_assumption_pct": 0.0,
    "monte_carlo_target_capital": 500.0,
    "monte_carlo_simulations": 1000,
    "capital_buckets": {
        "stock_day_bucket_fraction": 0.50,
        "crypto_night_bucket_fraction": 0.30,
        "reserve_cash_bucket_fraction": 0.15,
        "emergency_cash_bucket_fraction": 0.05,
    },
    "crypto_push_pull": {
        "momentum_threshold_1h": 0.004,
        "momentum_threshold_3h": 0.006,
        "max_volatility": 0.10,
        "max_hold_hours": 12,
        "edge_min_over_cost": 1.2,
        "stop_loss_pct": 0.02,
        "take_profit_pct": 0.03,
    },
    "ranking": {
        "w_signal_strength": 0.20,
        "w_confidence": 0.20,
        "w_edge_over_cost": 0.25,
        "w_spread_quality": 0.15,
        "w_liquidity": 0.10,
        "w_volatility_anomaly": 0.05,
        "w_memory_penalty": 0.03,
        "w_correlation_penalty": 0.02,
    },
    "portfolio": {
        "execute_top_n_signals": 1,
        "max_concurrent_positions": 2,
        "max_total_exposure_pct": 40.0,
        "reserve_cash_pct": 60.0,
        "max_same_direction_positions": 2,
        "correlation_block_threshold": 0.70,
        "correlation_lookback_hours": 720,
        "signal_score_min": 0.35,
    },
    "cost": {
        "taker_fee_pct": 0.25,
        "maker_fee_pct": 0.15,
        "slippage_buffer_major_pct": 0.10,
        "slippage_buffer_alt_pct": 0.20,
        "slippage_buffer_meme_pct": 0.30,
        "edge_multiplier_paper": 2.0,
        "edge_multiplier_pre_live": 2.2,
        "edge_multiplier_tiny_live": 2.5,
        "edge_multiplier_live": 2.5,
        "min_expected_move_pct": 0.15,
    },
    "risk": {
        "risk_pct_paper": 0.5,
        "risk_pct_pre_live": 0.5,
        "risk_pct_tiny_live": 0.25,
        "risk_pct_live": 1.0,
        "atr_period": 14,
        "k_atr_major": 2.0,
        "k_atr_alt": 2.0,
        "k_atr_meme": 2.5,
        "stop_cost_floor_multiplier": 2.0,
        "max_exposure_per_symbol_pct": 15.0,
        "max_total_crypto_exposure_pct": 40.0,
        "emergency_cash_floor_pct": 10.0,
    },
    "execution": {
        "paper_orders_enabled": False,
        "live_orders_enabled": False,
        "require_operator_arm_for_paper": True,
        "order_type_default": "marketable_limit_ioc",
        "max_orders_per_cycle": 1,
        "max_orders_per_hour": 2,
        "max_orders_per_day": 6,
        "min_seconds_between_orders_per_symbol": 300,
        "limit_price_buffer_bps_major": 15,
        "limit_price_buffer_bps_alt": 25,
        "limit_price_buffer_bps_meme": 40,
    },
    "cooldown": {
        "symbol_after_loss_minutes": 60,
        "symbol_after_two_losses_minutes": 180,
        "symbol_after_three_losses_minutes": 720,
        "broker_rejection_minutes": 30,
        "price_band_cancel_minutes": 15,
        "spread_spike_minutes": 30,
        "liquidity_drop_minutes": 60,
        "ai_high_warning_minutes": 30,
        "ai_critical_manual_ack": True,
        "account_three_losses_one_hour_minutes": 120,
        "daily_drawdown_minutes": 1440,
        "weekly_drawdown_minutes": 10080,
        "exponential_backoff_enabled": True,
        "exponential_backoff_cap_minutes": 1440,
    },
    "kill": {
        "daily_drawdown_pct": 2.0,
        "weekly_drawdown_pct": 5.0,
        "max_drawdown_pct": 15.0,
        "reconciliation_drift_usd": 5.0,
        "broker_error_rate_threshold": 0.25,
        "heartbeat_max_seconds": 600,
        "spread_spike_multiplier": 2.5,
        "symbol_consecutive_loss_limit": 3,
        "manual_master_active": False,
    },
    "promotion": {
        "current_stage": "PAPER",
        "human_approval_required": True,
        "stages": {
            "PAPER": {
                "portfolio": {
                    "execute_top_n_signals": 1,
                    "max_concurrent_positions": 2,
                    "max_total_exposure_pct": 40.0,
                    "reserve_cash_pct": 60.0,
                },
                "risk": {"risk_pct_paper": 0.5},
            },
            "PRE_LIVE": {
                "portfolio": {
                    "execute_top_n_signals": 1,
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 25.0,
                    "reserve_cash_pct": 75.0,
                },
            },
            "TINY_LIVE": {
                "portfolio": {
                    "execute_top_n_signals": 1,
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 15.0,
                    "reserve_cash_pct": 85.0,
                },
                "risk": {"risk_pct_tiny_live": 0.25},
            },
            "STANDARD_LIVE": {
                "portfolio": {
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 15.0,
                },
                "risk": {"risk_pct_live": 1.0},
            },
        },
        "criteria": {
            "paper_to_pre_live": {
                "min_calendar_days": 90,
                "min_closed_trades": 100,
                "max_drawdown_pct": 15.0,
                "reconciliation_drift_days": 30,
            },
        },
    },
    "symbol_tiers": {
        "tier_rules": [
            {"pattern": "BTC", "tier": "TIER_MAJOR"},
            {"pattern": "ETH", "tier": "TIER_MAJOR"},
            {"pattern": "SOL", "tier": "TIER_MAJOR"},
            {"pattern": "LINK", "tier": "TIER_ALT"},
            {"pattern": "AVAX", "tier": "TIER_ALT"},
            {"pattern": "DOGE", "tier": "TIER_MEME_SUPPORTED"},
            {"pattern": "SHIB", "tier": "TIER_MEME_SUPPORTED"},
            {"pattern": "PEPE", "tier": "TIER_WATCH"},
            {"pattern": "BONK", "tier": "TIER_WATCH"},
            {"pattern": "FLOKI", "tier": "TIER_WATCH"},
            {"pattern": "WIF", "tier": "TIER_WATCH"},
        ],
        "meme_extra_edge_multiplier": 1.25,
        "meme_max_exposure_pct": 8.0,
        "meme_max_spread_pct": 0.004,
    },
    "ai_enabled": True,
    "ai_monthly_budget_usd": 5.0,
    "ai_max_reviews_per_day": 8,
    "ai_max_tokens_per_review": 2048,
    "ai_min_seconds_between_reviews": 120,
    "ai_model_quick": "gemini-3.5-flash",
    "ai_model_deep": "gemini-3.5-flash",
    "ai_estimated_cost_per_review_usd": 0.002,
    "locked_safety_caps": {
        "max_risk_per_trade": 0.02,
        "daily_loss_limit_pct": 0.05,
        "live_trading_enabled": False,
    },
    "locked_config_keys": list(
        {
            "promotion.current_stage",
            "execution.live_orders_enabled",
            "live_trading_enabled",
            "kill.manual_master_active",
        }
    ),
}

RISK_CAGE_RULES = [
    "Stop-loss required — ATR-based when data available",
    "Risk per trade from promotion stage (paper 0.5%)",
    "Edge must exceed round-trip cost × stage multiplier",
    "Portfolio Top-N gate — default 1 signal per cycle on $200 account",
    "No short selling — sell only with broker position",
    "Meme/watch-only symbols cannot reach execution path",
    "AI cannot change promotion stage or submit orders",
    "Paper orders disabled until operator enables execution.paper_orders_enabled",
]
