"""Default risk/config — all thresholds in DB, versioned via ConfigManager."""

DEFAULT_CONFIG = {
    "config_version": 7,
    "max_risk_per_trade": 0.005,
    "max_position_size_pct": 1.0,
    "max_open_positions": 0,
    "daily_loss_limit_pct": 0.02,
    "weekly_loss_limit_pct": 0.05,
    "max_drawdown_limit_pct": 0.15,
    "max_spread_pct": 0.005,
    "min_liquidity_score": 40,
    "max_loss_streak": 5,
    "confidence_threshold": 0.6,
    "stop_loss_required": True,
    "take_profit_required": False,
    "kill_switch_active": False,
    "paper_trading_only": True,
    "live_trading_enabled": False,
    "min_order_notional_usd": 1.0,
    "opening_range_minutes": 30,
    "pairs_z_entry": 2.0,
    "pairs_z_exit": 0.5,
    "slippage_assumption_pct": 0.001,
    "spread_assumption_pct": 0.0005,
    "fee_assumption_pct": 0.0,
    "monte_carlo_target_capital": 500.0,
    "monte_carlo_simulations": 1000,
    "capital_buckets": {
        "stock_day_bucket_fraction": 0.50,
        "crypto_night_bucket_fraction": 0.30,
        "reserve_cash_bucket_fraction": 0.15,
        "emergency_cash_bucket_fraction": 0.05,
    },
    "crypto_push_pull": {
        "momentum_threshold_1h": 0.004,
        "momentum_threshold_3h": 0.006,
        "max_volatility": 0.10,
        "max_hold_hours": 12,
        "edge_min_over_cost": 1.2,
        "stop_loss_pct": 0.02,
        "take_profit_pct": 0.03,
    },
    "shadow_league": {
        "enabled": True,
        "min_quality_for_observation": 0.35,
        "min_quality_for_shadow_trade": 0.42,
        "shadow_proven_min_wins": 2,
        "shadow_proven_min_closed": 3,
        "max_open_shadow_trades": 20,
        "max_hold_hours": 8,
        "min_hold_seconds": 90,
        "win_threshold_bps": 5.0,
        "loss_threshold_bps": -5.0,
        "allow_crypto": True,
        "allow_stock": True,
        "stock_requires_execution_grade_for_paper_candidate": True,
        "never_submit_broker_orders": True,
        "never_counts_as_broker_evidence": True,
    },
    "push_pull": {
        "push_strength_min": 0.004,
        "body_pct_min": 0.35,
        "volume_spike_min": 1.5,
        "max_spread_bps": 50.0,
        "min_edge_after_cost_bps": 50.0,
        "max_quote_age_seconds": 30.0,
        "max_bar_age_minutes": 120.0,
        "enter_threshold": 0.70,
        "paper_exploration_enter_floor": 0.42,
        "paper_exploration_min_quality": 0.38,
        "min_trade_quality": 0.60,
        "atr_stop_multiplier": 2.0,
        "atr_period": 14,
        "profit_target_bps": 300.0,
        "trailing_giveback_bps": 100.0,
        "timeout_minutes": 240,
        "overextension_max": 3.0,
        "cooldown_minutes_after_loss": 60,
        "pump_dump_atr_z_threshold": 4.0,
        "max_daily_loss_pct": 2.0,
        "max_strategy_drawdown_pct": 8.0,
        "max_rejection_rate": 0.5,
        "dynamic_exits": {
            "atr_period": 14,
            "atr_stop_multiplier": 2.0,
            "fallback_stop_pct": 0.02,
            "min_stop_bps": 35.0,
            "max_stop_bps": 500.0,
            "spread_cushion_multiplier": 3.0,
            "quick_scalp_enabled": True,
            "base_target_r_multiple": 0.9,
            "max_target_r_multiple": 1.8,
            "profit_target_bps": 120.0,
            "min_target_bps_major": 55.0,
            "min_target_bps_alt": 80.0,
            "min_target_bps_meme": 100.0,
            "target_spread_multiplier": 4.0,
            "max_quick_target_bps": 180.0,
            "trailing_giveback_bps": 45.0,
        },
        "long_structure": {
            "enabled": True,
            "min_bullish_pattern_confidence": 0.45,
            "max_negative_momentum_without_pattern": -0.0005,
        },
    },
    "paper_ratchet": {
        "enabled": True,
        "relax_entry_stale_bar": True,
        "relax_entry_min_bars": 8,
        "arm_trailing_after_profit_bps": 25.0,
        "giveback_bps": 40.0,
        "initial_stop_pct": 0.02,
        "buy_low_pullback_bps": 80.0,
    },
    "allocator": {
        "paper_trade_notional_min_usd": 20.0,
        "paper_trade_notional_max_usd": 40.0,
    },
    "ranking": {
        "ai_managed": True,
        "min_rank_score": 0.28,
        "w_signal_strength": 0.20,
        "w_confidence": 0.20,
        "w_edge_over_cost": 0.25,
        "w_spread_quality": 0.15,
        "w_liquidity": 0.10,
        "w_volatility_anomaly": 0.05,
        "w_memory_penalty": 0.03,
        "w_correlation_penalty": 0.02,
    },
    "universe_ranking": {
        "w_liquidity": 0.25,
        "w_spread": 0.15,
        "w_volume_spike": 0.20,
        "w_atr": 0.15,
        "w_freshness": 0.15,
        "w_cost_efficiency": 0.10,
        "min_rank_score": 0.28,
        "max_spread_bps": 80.0,
        "max_bar_age_seconds": 900.0,
    },
    "portfolio": {
        "execute_top_n_signals": 0,
        "max_concurrent_positions": 0,
        "max_total_exposure_pct": 100.0,
        "reserve_cash_pct": 5.0,
        "max_same_direction_positions": 2,
        "correlation_block_threshold": 0.70,
        "correlation_lookback_hours": 720,
        "signal_score_min": 0.35,
    },
    "cost": {
        "taker_fee_pct": 0.25,
        "maker_fee_pct": 0.15,
        "slippage_buffer_major_pct": 0.10,
        "slippage_buffer_alt_pct": 0.20,
        "slippage_buffer_meme_pct": 0.30,
        # Research cost model v2 (no double-count). Operator-visible; round-trip =
        # spread + slippage*2 + fee*2, clamped [min_cost_floor_bps, max_cost_cap_bps].
        # default_fee_bps = 25 preserves the existing conservative taker_fee_pct (0.25%)
        # per side — do NOT lower it without re-running the old-vs-new shadow analysis.
        "cost_model_version": "v2_components_no_double_count",
        "default_spread_bps_by_tier": {"TIER_MAJOR": 8.0, "TIER_ALT": 20.0, "TIER_MEME_SUPPORTED": 40.0, "TIER_MEME": 40.0},
        "default_slippage_bps_by_tier": {"TIER_MAJOR": 4.0, "TIER_ALT": 10.0, "TIER_MEME_SUPPORTED": 25.0, "TIER_MEME": 25.0},
        "default_fee_bps": 25.0,
        "conservative_cost_multiplier": 1.0,
        "min_cost_floor_bps": 8.0,
        "max_cost_cap_bps": 150.0,
        "spread_model": "tiered_pct",
        "edge_multiplier": 2.0,
        "edge_multiplier_paper": 1.35,
        "edge_multiplier_pre_live": 2.2,
        "edge_multiplier_tiny_live": 2.5,
        "edge_multiplier_live": 2.5,
        "min_expected_move_pct": 0.15,
    },
    "alpha_factory": {
        "min_sample_size": 5,
        "min_profit_factor": 1.05,
        "session_min_sample_size": 5,
        # Paper-exploration lane for near-miss alpha candidates. PAPER-ONLY learning lane that
        # sits BELOW paper_candidate. It can never enable live trading, never bypass the cage,
        # and never promote a near-miss directly to paper_candidate. Tiny notional, capped.
        "paper_exploration": {
            "allow_paper_exploration_near_misses": True,
            "exploration_max_notional_usd": 12.0,
            # Hard operator-settable ceiling for the exploration notional cap (paper-only).
            # The set-cap endpoint rejects anything above this. Never raise for live trading.
            "exploration_cap_max_usd": 25.0,
            "exploration_max_positions": 1,
            "exploration_max_entries_per_day": 3,
            "exploration_min_sample_size": 50,
            "exploration_min_edge_after_cost_bps": -5.0,
            "exploration_required_session_metrics": True,
            "exploration_live_forbidden": True,
            # Promotion exploration_candidate -> paper_candidate requires real closed evidence.
            "exploration_promote_min_closed_trades": 20,
            "exploration_promote_min_profit_factor": 1.10,
            "exploration_promote_max_drawdown_pct": 35.0,
            # Broker-compatible sizing. A probe is only attempted when its notional clears the
            # broker minimum; otherwise it is skipped (never an invalid broker submit). The cap
            # is NOT raised silently to reach the broker minimum.
            "allow_notional_orders": True,
            "allow_qty_orders": True,
            "broker_min_buffer_pct": 2.0,
            "skip_candidate_if_min_notional_exceeds_cap": True,
            "allow_cap_raise_to_broker_min": False,
        },
    },
    "risk": {
        "risk_pct_paper": 0.5,
        "risk_pct_pre_live": 0.5,
        "risk_pct_tiny_live": 0.25,
        "risk_pct_live": 1.0,
        "atr_period": 14,
        "k_atr_major": 2.0,
        "k_atr_alt": 2.0,
        "k_atr_meme": 2.5,
        "stop_cost_floor_multiplier": 2.0,
        "max_exposure_per_symbol_pct": 100.0,
        "max_total_crypto_exposure_pct": 100.0,
        "emergency_cash_floor_pct": 5.0,
        "reconciliation_drift_halt_bps": 5.0,
    },
    "execution": {
        "paper_orders_enabled": False,
        "live_orders_enabled": False,
        "require_operator_arm_for_paper": True,
        "order_type_default": "marketable_limit_ioc",
        "crypto_paper_recipe": "limit_ioc_qty",
        "alpaca_crypto_min_notional_usd": 10.0,
        "alpaca_min_notional_buffer_usd": 0.5,
        "buying_power_buffer_pct": 2.0,
        "max_orders_per_cycle": 0,
        "max_orders_per_hour": 0,
        "max_orders_per_day": 0,
        "min_seconds_between_orders_per_symbol": 300,
        "quote_max_age_seconds": 30,
        "limit_price_buffer_bps_major": 15,
        "limit_price_buffer_bps_alt": 25,
        "limit_price_buffer_bps_meme": 40,
    },
    "cooldown": {
        "symbol_after_loss_minutes": 60,
        "symbol_after_two_losses_minutes": 180,
        "symbol_after_three_losses_minutes": 720,
        "broker_rejection_minutes": 30,
        "price_band_cancel_minutes": 15,
        "spread_spike_minutes": 30,
        "liquidity_drop_minutes": 60,
        "ai_high_warning_minutes": 30,
        "ai_critical_manual_ack": True,
        "account_three_losses_one_hour_minutes": 120,
        "daily_drawdown_minutes": 1440,
        "weekly_drawdown_minutes": 10080,
        "exponential_backoff_enabled": True,
        "exponential_backoff_cap_minutes": 1440,
    },
    "kill": {
        "daily_drawdown_pct": 2.0,
        "weekly_drawdown_pct": 5.0,
        "max_drawdown_pct": 15.0,
        "reconciliation_drift_usd": 5.0,
        "broker_error_rate_threshold": 0.25,
        "heartbeat_max_seconds": 600,
        "spread_spike_multiplier": 2.5,
        "symbol_consecutive_loss_limit": 3,
        "manual_master_active": False,
    },
    "promotion": {
        "current_stage": "PAPER",
        "human_approval_required": True,
        "stages": {
            "PAPER": {
                "portfolio": {
                    "execute_top_n_signals": 0,
                    "max_concurrent_positions": 0,
                    "max_total_exposure_pct": 100.0,
                    "reserve_cash_pct": 5.0,
                },
                "risk": {"risk_pct_paper": 0.5},
            },
            "PRE_LIVE": {
                "portfolio": {
                    "execute_top_n_signals": 1,
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 25.0,
                    "reserve_cash_pct": 75.0,
                },
            },
            "TINY_LIVE": {
                "portfolio": {
                    "execute_top_n_signals": 1,
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 15.0,
                    "reserve_cash_pct": 85.0,
                },
                "risk": {"risk_pct_tiny_live": 0.25},
            },
            "STANDARD_LIVE": {
                "portfolio": {
                    "max_concurrent_positions": 1,
                    "max_total_exposure_pct": 15.0,
                },
                "risk": {"risk_pct_live": 1.0},
            },
        },
        "criteria": {
            "paper_to_pre_live": {
                "min_calendar_days": 90,
                "min_closed_trades": 100,
                "max_drawdown_pct": 15.0,
                "reconciliation_drift_days": 30,
            },
        },
    },
    "symbol_tiers": {
        "tier_rules": [
            {"pattern": "BTC", "tier": "TIER_MAJOR"},
            {"pattern": "ETH", "tier": "TIER_MAJOR"},
            {"pattern": "SOL", "tier": "TIER_MAJOR"},
            {"pattern": "LINK", "tier": "TIER_ALT"},
            {"pattern": "AVAX", "tier": "TIER_ALT"},
            {"pattern": "DOGE", "tier": "TIER_MEME_SUPPORTED"},
            {"pattern": "SHIB", "tier": "TIER_MEME_SUPPORTED"},
            {"pattern": "PEPE", "tier": "TIER_WATCH"},
            {"pattern": "BONK", "tier": "TIER_WATCH"},
            {"pattern": "FLOKI", "tier": "TIER_WATCH"},
            {"pattern": "WIF", "tier": "TIER_WATCH"},
        ],
        "meme_extra_edge_multiplier": 1.25,
        "meme_max_exposure_pct": 8.0,
        "meme_max_spread_pct": 0.004,
    },
    "memory": {
        "enabled": True,
        "pattern_window_cycles": 20,
        "min_occurrences_for_pattern": 3,
        "max_memory_penalty": 0.15,
        "require_human_approval_for_config_changes": True,
    },
    "research": {
        "auto_backtest_enabled": False,
        "auto_backtest_max_runs_per_day": 5,
        "auto_backtest_symbols": ["BTC/USD", "ETH/USD", "DOGE/USD"],
        "auto_backtest_families": ["crypto_push_pull", "mean_reversion", "volatility_breakout"],
        "auto_backtest_time_budget_minutes": 30,
        "auto_backtest_requires_market_closed": True,
        "auto_backtest_skip_if_paper_position_open": True,
        "auto_backtest_cost_budget_usd": 0.0,
        "train_window_days": 30,
        "test_window_days": 14,
        "walk_forward_step_days": 7,
        "min_trades_per_window": 5,
        "min_total_trades": 20,
        "min_out_of_sample_windows": 2,
        "min_bars_for_backtest": 50,
        "min_bars_for_walk_forward": 120,
        "sweep_max_combinations": 24,
        "promotion_min_win_rate": 0.45,
        "promotion_min_profit_factor": 1.1,
        "promotion_max_drawdown_pct": 25.0,
        "low_sample_trade_threshold": 10,
    },
    "strategy_promotion": {
        "profile": "micro_account_safe",
        "eligibility_earliest_days": 7,
        "eligibility_latest_days": 14,
        "min_valid_observations": 5,
        "max_open_positions_micro": 3,
        "max_meme_positions": 1,
    },
    "memory_weights": {
        "confirmation_bonus": 0.1,
        "failure_penalty": 0.15,
    },
    "ai_enabled": True,
    # Phase 0 quarantine: Strategy Reviewer is post-hoc commentary only (disabled in cycle by default).
    "legacy_strategy_reviewer_enabled": False,
    "strategy_reviewer": {"enabled": False},
    "evidence_memory": {"enabled": True},
    "legacy_ai_fund_manager": {"disabled_by_default": True},
    "legacy_sentience": {"disabled_by_default": True},
    "ai_monthly_budget_usd": 5.0,
    "ai_max_reviews_per_day": 8,
    "ai_max_tokens_per_review": 2048,
    "ai_min_seconds_between_reviews": 120,
    "ai_model_quick": "gemini-3.5-flash",
    "ai_model_deep": "gemini-3.5-flash",
    "ai_estimated_cost_per_review_usd": 0.002,
    "locked_safety_caps": {
        "max_risk_per_trade": 0.02,
        "daily_loss_limit_pct": 0.05,
        "live_trading_enabled": False,
    },
    "memory_policy": {
        "consolidation_threshold_total_raw_memories": 100,
        "consolidation_threshold_per_strategy": 25,
        "archive_raw_after_consolidation": True,
        "graph_default_show_raw_memories": False,
        "max_default_graph_nodes": 50,
    },
    "meme_spike_detector": {
        "block_pump_dump_risk": True,
        "allow_tiny_training_on_spike": False,
    },
    "training_aggressive_micro": {
        "enabled_profile": True,
        "max_trades_per_day": 8,
        "default_notional_usd": 10,
        "no_averaging_down": True,
        "no_duplicate_symbol": True,
    },
    "aggressive_paper_learning": {
        "mode_enabled": False,
        "max_experiment_notional_per_trade_usd": 0,
        "default_experiment_notional_usd": 10,
        "max_experiment_positions_total": 0,
        "max_experiment_trades_per_day": 0,
        "max_experiment_trades_per_strategy_per_day": 0,
        "max_open_experiment_positions": 0,
        "use_capital_allocator": True,
        "max_daily_experiment_loss_pct": 5.0,
        "max_weekly_experiment_loss_pct": 10.0,
        "meme_coin_max_hold_minutes": 240,
        "major_crypto_max_hold_hours": 48,
        "require_stop_loss": True,
        "require_time_stop": True,
        "require_take_profit_or_exit_rule": True,
        "require_spread_check": True,
        "require_liquidity_check": True,
        "require_position_monitor": True,
        "allow_live": False,
        "block_pump_dump_risk": True,
        "push_pull_max_hold_minutes": 30,
    },
    "capital_allocator": {
        "stock_target_weight": 0.35,
        "crypto_target_weight": 0.45,
        "cash_reserve_weight": 0.05,
        "min_cash_reserve": 1,
        "crypto_night_reserve_weight": 0.35,
        "max_single_stock_exposure_weight": 0.95,
        "max_single_crypto_exposure_weight": 0.95,
        "max_asset_class_exposure_weight": 1.0,
        "stock_close_cutoff_minutes": 45,
        "correlation_penalty_enabled": True,
        "volatility_scaling_enabled": True,
        "allow_crypto_during_stock_hours": True,
        "allow_stocks_after_hours": False,
        "preferred_crypto_quote_currency": "USD",
        "repeated_reject_cooldown_enabled": True,
        "max_repeated_rejects_per_symbol": 3,
        "broker_rate_limit_backoff_enabled": True,
        "duplicate_symbol_protection_enabled": True,
        "allow_scaling_same_symbol_if_strategy_approved": False,
        "operator_emergency_max_open_positions": 0,
        "broker_uncertainty_buffer_pct": 0.05,
        "min_trade_notional_usd": 1,
    },
    "autonomous_paper_learning": {
        "mode_enabled": False,
        "scheduler_enabled": False,
        "scheduler_interval_seconds": 600,
        "max_paper_trades_per_day": 0,
        "max_paper_notional_per_trade_usd": 0,
        "default_paper_notional_usd": 5,
        "max_open_paper_positions": 0,
        "use_capital_allocator": True,
        "max_daily_paper_loss_pct": 5.0,
        "max_weekly_paper_loss_pct": 10.0,
        "max_rejected_orders_per_day": 0,
        "rejection_cooldown_minutes": 15,
        "max_scheduler_ticks_per_day": 0,
        "broker_error_pause_after": 3,
        # --- Hard safety caps + telemetry references (survive allocator mode) ---
        # Open-positions, per-hour entry, and per-cycle caps remain HARD blocks in the
        # execution cage. The two DAILY COUNT values below are now TELEMETRY / circuit
        # references only — the fixed "stop after N entries/ticks per day" behaviour was
        # replaced by the adaptive opportunity budget (opportunity_budget below) plus
        # scheduler pacing/backoff. They are kept generous so they never act as a daily
        # stop; the real safety ceiling is opportunity_budget.absolute_max_orders_per_day.
        "absolute_max_scheduler_ticks_per_day": 1000,   # telemetry only; pacing controls cadence
        "absolute_max_new_entries_per_day": 200,        # telemetry only; adaptive budget gates entries
        "absolute_max_new_entries_per_hour": 6,         # HARD anti-spam pacing cap (raised from 2)
        "absolute_max_orders_per_cycle": 1,             # HARD per-cycle cap
        "absolute_max_open_positions": 3,               # HARD cap (kept)
        "auto_pause_after_consecutive_broker_errors": 3,
        "auto_pause_after_consecutive_rejections": 3,
        # --- Adaptive opportunity budget (replaces the fixed daily trade-count cap) ---
        # app/services/adaptive_opportunity_budget.py — risk-based gate for one new entry.
        # The circuit-breaker is a generous safety ceiling, NOT a strategy trade cap.
        "opportunity_budget": {
            "enabled": True,
            "max_daily_risk_pct": 4.0,
            "max_open_risk_pct": 4.0,
            "min_edge_after_cost_bps": 15.0,
            "min_signal_score": 0.50,
            "default_trade_risk_pct": 1.0,
            "absolute_max_orders_per_day": 200,
            "max_broker_error_streak": 3,
            "max_rejection_streak": 3,
        },
        # --- Deterministic protections (Freqtrade-style concepts; no dependency) ---
        # app/services/paper_trade_protections.py — entry-only; exits never affected.
        "protections": {
            "enabled": True,
            "max_drawdown_block_pct": 12.0,
            "stoploss_guard_lookback_hours": 6.0,
            "stoploss_guard_max_stops": 3,
            "low_profit_min_trades": 3,
            "low_profit_net_threshold_usd": 0.0,
            "low_profit_cooldown_hours": 12.0,
            "cooldown_after_exit_minutes": 30,
            "cooldown_strong_signal_score": 0.80,
            "churn_lookback_hours": 6.0,
            "churn_max_flat_trades": 4,
            "churn_required_edge_after_cost_bps": 40.0,
        },
        "no_averaging_down": True,
        "no_duplicate_symbol_buy": True,
        "duplicate_recent_order_window_minutes": 60,
        "block_new_entry_if_unmanaged_position": True,
        "auto_heal_missing_exit_plans": True,
        "auto_pause_on_unmanaged_position": False,
        "emergency_max_hold_hours": 24,
        # --- Fee-aware max-hold (TASK 5): extend a fee-uncovered hold while the signal
        # is still valid, bounded by a hard time ceiling. Stop-loss / invalidation /
        # loss-band exits always fire immediately and are unaffected. ---
        "absolute_max_hold_hours": 72,
        "max_extension_count": 3,
        "max_extension_minutes": 60,
        "max_hold_round_trip_cost_bps": 40,
        # --- Spread policy (entry cooldown/rotation + exit escalation; never traps exits) ---
        "spread_policy": {
            "spread_widened_repeat_threshold": 3,
            "spread_widened_lookback_minutes": 30,
            "spread_cooldown_minutes": 30,
            "exit_spread_tolerance_multiplier": 3.0,
            "max_exit_spread_delay_minutes": 10,
            "max_failed_exit_attempts_before_escalation": 3,
            "freeze_new_entries_on_unresolved_exit": True,
        },
        # --- Auto memory consolidation (raw -> visible learned memories each tick) ---
        "memory_consolidation": {
            "auto_enabled": True,
            "auto_interval_minutes": 30,
        },
        # --- Idle autonomous research/backtest worker (paper-only, advisory; never trades) ---
        "autonomous_research": {
            "autonomous_backtest_worker_enabled": True,
            "idle_research_max_runs_per_hour": 6,
            "idle_research_max_runtime_seconds": 20,
            "idle_research_cooldown_minutes": 5,
            "idle_research_min_sample_size": 5,
        },
        "refresh_market_data_before_tick": True,
        "refresh_stocks_during_market_hours": True,
        "refresh_lookback_hours": 36,
        "max_unrealized_loss_usd": 4.0,
        "max_unrealized_loss_pct": 1.5,
        "run_scanners_each_tick": True,
        "run_backtest_lab_every_n_ticks": 12,
        "backtest_lab_limit": 2,
        # Two-loop heartbeat model. The FAST heartbeat runs every tick: it manages exits,
        # refreshes quotes/positions, and updates risk state — but NEVER forces a new entry.
        # New entries are only considered on the SLOWER decision loop (every N ticks) and only
        # when backtest evidence exists. These gates are ADDITIVE (they can only block more
        # entries, never loosen safety).
        "heartbeat": {
            "enabled": True,
            "manage_exits_every_tick": True,
            "force_entries_every_candle": False,
            "decision_loop_interval_ticks": 4,
            "require_backtest_evidence_for_entry": True,
        },
        # --- Optional daily export (off by default). When enabled the scheduler
        # persists one compact diagnostics snapshot per day and prunes to the
        # newest N; the full bundle is always available on demand. ---
        "daily_export_enabled": False,
        "daily_export_retention": 14,
    },
    "confidence": {
        "weights": {
            "trade_performance": 0.25,
            "execution_quality": 0.2,
            "strategy_validation": 0.15,
            "memory_learning": 0.15,
            "risk_discipline": 0.15,
            "data_quality": 0.1,
        },
        "min_sample_trades_for_strategy": 3,
        "tiny_live_candidate_threshold": 76,
        "promotion_confidence_threshold": 61,
    },
    "stock_lane": {
        # disabled / readiness_only / paper_allowed_with_fresh_data / sip_required.
        # Default readiness_only: equities are scanned/readiness-checked but cannot place paper
        # entries during paper_validation_run_001 until the data-feed policy is approved.
        "mode": "readiness_only",
    },
    "promotion_readiness": {
        "min_paper_days": 7,
        "min_closed_paper_trades": 5,
        "min_expectancy_pct": 0.0,
        "max_drawdown_pct": 15.0,
        "min_confidence_for_tiny_live": 61,
    },
    "universe": {
        "mode": "hybrid_radar",
        "allow_curated_debug": True,
        "scan_all_alpaca_crypto": True,
        "scan_usd_crypto_first": True,
        "include_alt_crypto_watch": True,
        "include_social_movers": True,
        "include_stock_market_when_open": True,
        "speculative_paper_exploration": True,
        "max_execution_shortlist": 0,
        "max_scanned_symbols_per_cycle": 0,
        "max_ranked_symbols_per_cycle": 0,
        "trade_all_eligible": True,
        "dynamic_max_crypto": 36,
        "dynamic_max_stocks": 30,
        "require_1m_fresh_for_shortlist": False,
        "allow_zero_volume_cached_bars_for_paper": True,
        "max_bar_staleness_hours": 72,
        "skip_live_quote_for_ranking": True,
    },
    "exploration": {
        "enabled": True,
        "max_trade_notional_usd": 0.0,
        "max_positions": 0,
        "dynamic_formula_mode": True,
        "require_stronger_edge": True,
        "require_stop": True,
        "require_fresh_quote": True,
        "require_exit_monitor": True,
        "cooldown_after_loss": True,
        "cooldown_after_spread_reject": True,
        "min_edge_multiplier_vs_major": 1.15,
    },
    "sentiment": {
        "enabled": False,
        "finbert_enabled": False,
        "reddit_enabled": False,
        "news_enabled": False,
        "max_adjustment_pct": 10,
        "influence_ranking": True,
        "influence_trading": False,
    },
    "fast_training": {
        "exit_only_enabled": False,
        "fast_training_loop_enabled": False,
        "fast_training_cycle_seconds": 20,
        "fast_training_max_scan_symbols": 40,
        "fast_training_execute_orders": False,
        "fast_training_default_notional_usd": 5,
        "fast_training_max_notional_usd": 10,
        "fast_training_max_trades_per_day": 0,
        "fast_training_max_open_positions": 0,
        "fast_training_daily_loss_cap_pct": 5,
        "fast_training_require_exit_monitor": True,
        "use_db_lease": True,
    },
    "v2": {
        "aggressive_mode": True,
        "skip_entry_safety_snapshot_gates": True,
        "scheduler_interval_seconds": 45,
    },
    "locked_config_keys": list(
        {
            "promotion.current_stage",
            "execution.live_orders_enabled",
            "live_trading_enabled",
            "kill.manual_master_active",
        }
    ),
}

RISK_CAGE_RULES = [
    "Stop-loss required — ATR-based when data available",
    "Risk per trade from promotion stage (paper 0.5%)",
    "Edge must exceed round-trip cost × stage multiplier",
    "Portfolio Top-N gate — default 1 signal per cycle on $200 account",
    "No short selling — sell only with broker position",
    "Meme/watch-only symbols cannot reach execution path",
    "AI cannot change promotion stage or submit orders",
    "Paper orders disabled until operator enables execution.paper_orders_enabled",
]
